services:
  gitaction_backend:
    container_name: gitaction_backend
    image: gitaction_backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/app
      - /app/node_modules

  gitaction_frontend:
    container_name: gitaction_frontend
    image: gitaction_frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
